---
format: gfm
---

<!-- README.md is generated from README.qmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# adagraph

<!-- badges: start -->
<!-- badges: end -->

Design a two-stage adaptive trial using a graph-based closed-testing sequence, while controlling the FWER using the conditional error rate method.

## Installation

You can install the development version of adagraph from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("nebtu/adagraph")
```

## Example

```{r example}
library(adagraph)

alpha_spending_f <- function(x, t) 2 - 2 * pnorm(qnorm(1 - x / 2) / sqrt(t))
design <- cer_design(
  correlation = rbind(H1 = c(1, NA), H2 = c(NA, 1)),
  weights = c(2 / 3, 1 / 3),
  alpha = 0.05,
  test_m = rbind(c(0, 1), c(1, 0)),
  alpha_spending_f = alpha_spending_f,
  t = 0.5
)


design <- cer_interim_test(design, c(0.001, 0.02)) |>
  cer_drop_hypotheses(c(TRUE, FALSE)) |>
  cer_adapt_bounds() |>
  cer_final_test(c(NA, 0.01))

design
```

