# note that second stage depends on ad_n_table being set
# TODO: remove n=0 rows in data_spec, make sure that NA is returned for not
# calculated p-values

#' Get a data generating function for simulating a trial design
#'
#' Generates a data generating function that give p-values from normally
#' distributed or binary data for use in the `sim_trial()` function.
#'
#' This gives back a function, which takes as its arguments a number n and a
#' trial_design object and returns a matrix of n * "number of hypotheses"
#' p-values. Each of those p-values is generated by drawing values for each
#' patient as specified by the design object.
#' For endpoint specified as continuous, the values are drawn from a
#' multivariate normal distribution, with the correlation between endpoints
#' given by `corr_endpoints` and the effect size by the group effect size from
#' `effect_sizes`. For binary endpoints, the same data is generated (with the
#' same correlation being applied), but instead of a mean, `effect_sizes`
#' specifies the percentage of responders, which is generated by using an
#' approrpiate cutoff for the continuous data.
#' The $p$-values generated are from a $t$-test for continous data and from a
#' two-proportion $Z$-test for binary data.
#'
#' The argument *`effect_sizes`* should be given in the same format as the `n_table` argument for the `trial_design()`, but instead of the column `n`, there should be a column named for each endpoint, giving the effect size (either as a normal mean or a response rate, for continous or binary data) for this specific group and arm.
#'
#' @param corr_endpoints correlation matrix specifying correlation between the
#'   endpoints
#' @param effect_sizes data frame specifying the effect in each arm and group.
#'   See also details
#' @param binary_endpoints which treatment endpoints are binary endpoints (all control
#'   endpoints referenced by those are also automatically treated as binary)
#' @param second_stage bolean, specify if the data is generated for the first or
#' second stage. If for the second stage, the `trial_adapt_n` function must have
#' been used on the `trial_design()` object being used.
#'
#' @return A function taking two arguments, see details
#'
#' @importFrom stats pnorm qnorm pt
#' @export
#'
#' @examples
#' alpha_spending_f <- function(x, t) 2 - 2 * pnorm(qnorm(1 - x / 2) / sqrt(t))
#'
#' design <- trial_design(
#'   endpoints = 2,
#'   n_table = data.frame(arm = c("control", "arm1"), n = c(10, 10)),
#'   weights = c(0.5, 0.5),
#'   test_m = rbind(c(0, 1), c(1, 0)),
#'   alpha = 0.025,
#'   alpha_spending_f = alpha_spending_f,
#'   t = 1 / 2,
#'   names_arms = "arm1",
#'   names_endpoints = c("cont", "bin")
#' )
#'
#' data_gen <- get_trial_data_gen(
#'  corr_endpoints = rbind(c(1, 0.5), c(0.5, 1)),
#'  effect_sizes = data.frame(arm = c("control", "arm1"), cont = c(0, 0.4), bin
#'  = c(0.2, 0.5)),
#'  binary_endpoints = "bin"
#' )
#'
#' data_gen(10, design)
get_trial_data_gen <- function(
  corr_endpoints,
  effect_sizes,
  binary_endpoints = character(0),
  second_stage = FALSE
) {
  function(n, design) {
    # get the relevant sample sizes
    if (second_stage) {
      n_table <- design[["ad_n_table"]]
    } else {
      n_table <- design[["n_table"]]
    }

    #use effect sizes for the normal distribution, and apply binary cutoff later
    effect_sizes[paste0(binary_endpoints, "_bin")] <- effect_sizes[
      binary_endpoints
    ]
    effect_sizes[binary_endpoints] <- 0

    # match with the effect sizes
    data_spec <- merge(
      n_table,
      effect_sizes,
      by = c("arm", design[["names_subgroups"]])
    )

    # generate data for each group combination
    data_list <- lapply(seq_len(nrow(data_spec)), function(i) {
      if (data_spec[i, "n"] == 0) {
        return(NULL)
      }

      means <- unlist(data_spec[i, design[["names_endpoints"]]])
      data <- array(
        mvtnorm::rmvnorm(
          data_spec[i, "n"] * n,
          mean = means,
          sigma = corr_endpoints
        ),
        dim = c(n, data_spec[i, "n"], design[["endpoints"]])
      )
      data <- aperm(data, c(2, 3, 1))
      # now the shape is (number of treated people, number of endpoints, number of runs)

      for (endpoint in binary_endpoints) {
        binary_index <- which(design[["names_endpoints"]] == endpoint)
        data[, binary_index, ] <- as.numeric(
          #would be coerced to numeric anyway, so make it explicit
          data[, binary_index, ] >
            qnorm(1 - data_spec[i, paste0(endpoint, "_bin")])
        )
      }

      data
    })

    hyp_assoc <- design[["hyp_assoc"]]
    # test, over each hypothesis separately
    p_values <- vapply(
      seq_len(nrow(hyp_assoc)),
      function(i) {
        arm <- hyp_assoc[i, "arm"]
        group <- hyp_assoc[i, "group"]
        endpoint <- hyp_assoc[i, "endpoint"]
        endpoint_index <- which(design[["names_endpoints"]] == endpoint)
        if (group == "Total") {
          group_filter <- TRUE
        } else {
          group_filter <- data_spec[[group]]
        }

        treat_filter <- data_spec[["arm"]] == arm & group_filter
        n_treat <- sum(data_spec[treat_filter, "n"])
        data_treat_list <- data_list[treat_filter]
        data_treat <- do.call(
          rbind,
          lapply(data_treat_list, function(d) {
            d[, endpoint_index, ]
          })
        )

        control_filter <- data_spec[["arm"]] == "control" & group_filter
        n_control <- sum(data_spec[control_filter, "n"])
        data_cont_list <- data_list[
          data_spec[["arm"]] == "control" & group_filter
        ]
        data_cont <- do.call(
          rbind,
          lapply(data_cont_list, function(d) {
            d[, endpoint_index, ]
          })
        )
        if (n_treat == 0 | n_control == 0) {
          return(rep(NA, n))
        }

        if (endpoint %in% binary_endpoints) {
          cont_prop <- colMeans(data_cont)
          treat_prop <- colMeans(data_treat)
          overall_prop <- colMeans(rbind(data_treat, data_cont))

          z <- (treat_prop - cont_prop) /
            sqrt(
              overall_prop *
                (1 - overall_prop) *
                ((1 / n_control) + (1 / n_treat))
            )
          p <- ifelse(is.na(z), 1, pnorm(z, lower.tail = FALSE))
        } else {
          cont_mean <- colMeans(data_cont)
          cont_var <- matrixStats::colVars(data_cont)
          treat_mean <- colMeans(data_treat)
          treat_var <- matrixStats::colVars(data_treat)

          t <- (treat_mean - cont_mean) /
            sqrt(
              (treat_var * (n_treat - 1) + cont_var * (n_control - 1)) /
                ((n_treat + n_control - 2)) *
                (1 / n_treat + 1 / n_control)
            )

          p <- pt(t, df = n_treat + n_control - 2, lower.tail = FALSE)
        }

        p
      },
      numeric(n)
    )

    p_values
  }
}
